# Metadata used when generating an iOS APP, for example.

# To find a certificate in the keychain
# certtool y | grep Joe Foo 

# to find a provisioning file in the provisioning directory
# ls -l ~/Library/MobileDevice/Provisioning\ Profiles

[package.metadata.signing]
signature = "Apple Development: "
provisioning_file = "bevy_provisioning_profile.mobileprovision"


