# Metadata used when generating an iOS APP, for example.
[package.metadata.signing]
signature = "Apple Development: Joe Foo (B6ADF9EUYT)"
provisioning_file = "bevy_provisioning_profile.mobileprovision"


